// actionTypes.js
export const START_UPDATE_POST = 'START_UPDATE_POST';
export const UPDATE_POST_OPTIMISTICALLY = 'UPDATE_POST_OPTIMISTICALLY';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_FAILURE = 'UPDATE_POST_FAILURE';
